const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * withAndroidNetworkSecurity — let the app actually reach a qBittorrent server.
 *
 * Android blocks two things by default that every self-hosted setup depends on,
 * and it blocks them *silently*: the request just fails, and axios reports a
 * bare "Network Error" with no hint that the platform refused it.
 *
 * 1. **Cleartext HTTP** — refused since API 28 for anything targeting it. A
 *    qBittorrent WebUI on a LAN address is almost always plain HTTP, so without
 *    this every server configured by IP is unreachable.
 *
 * 2. **User-installed CAs** — since Android 7, apps ignore certificates the
 *    user has installed on the device unless they opt in. Anyone running
 *    qBittorrent behind nginx/Traefik with their own internal CA therefore gets
 *    a TLS failure even though the phone's browser trusts the same certificate.
 *
 * `expo.android.usesCleartextTraffic` does NOT exist in the Expo config schema
 * (checked against @expo/config-types for SDK 57): setting it in app.config.js
 * is accepted, ignored, and produces a manifest with no cleartext permission —
 * the same silent-drop failure mode AGENTS.md warns about for qBittorrent API
 * parameters. It has to be done here.
 *
 * ## The trade-off in trusting user CAs
 *
 * Adding `<certificates src="user" />` means a CA installed on the device is
 * trusted by this app, which widens the man-in-the-middle surface: someone able
 * to install a CA profile on the phone could intercept qRemote's traffic. For a
 * tool whose entire job is talking to a server *you* run — often over a private
 * network, frequently behind your own CA — that is the right trade, and it is
 * what makes a reverse-proxy setup work without any native code. The
 * alternative is telling users their certificate is invalid when their browser
 * says otherwise.
 *
 * Note what this does NOT cover: a self-signed certificate that was never
 * installed on the device. That still needs the per-server "allow self-signed
 * certificate" toggle, which is backed by an iOS-only native module — see
 * docs/ANDROID.md "Known Android gaps".
 */

const CONFIG_FILE_NAME = 'network_security_config.xml';

const NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by plugins/withAndroidNetworkSecurity.js — do not edit.
  android/ is regenerated by \`expo prebuild\` and this file goes with it.
-->
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />
        </trust-anchors>
    </base-config>
</network-security-config>
`;

/** Write res/xml/network_security_config.xml into the generated project. */
function withNetworkSecurityConfigFile(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const xmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      await fs.promises.mkdir(xmlDir, { recursive: true });
      await fs.promises.writeFile(
        path.join(xmlDir, CONFIG_FILE_NAME),
        NETWORK_SECURITY_CONFIG,
        'utf8',
      );
      return cfg;
    },
  ]);
}

/** Point <application> at the config above. */
function withNetworkSecurityManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    application.$['android:networkSecurityConfig'] = '@xml/network_security_config';
    // Belt to the config's braces. The XML is authoritative on API 24+, but the
    // attribute is what older tooling and manifest readers look at, and having
    // both makes the intent obvious to anyone auditing the APK.
    application.$['android:usesCleartextTraffic'] = 'true';
    return cfg;
  });
}

module.exports = function withAndroidNetworkSecurity(config) {
  return withNetworkSecurityManifest(withNetworkSecurityConfigFile(config));
};
