const { withAppBuildGradle } = require('expo/config-plugins');

/**
 * withAndroidBuildTweaks — the three things `android/app/build.gradle` needs
 * that app.config.js has no field for.
 *
 * `android/` is generated by `expo prebuild` and git-ignored, so it cannot be
 * hand-edited: the next prebuild would silently drop the change. Anything that
 * must survive belongs here.
 *
 * 1. **A stable release signature.** The RN template's `release` build type is
 *    signed with `android/app/debug.keystore`, a file that is re-materialised
 *    by every prebuild. If that file ever differs between two prebuilds — a
 *    template bump, a different machine, CI — the signature changes, and
 *    Android refuses to install the new APK over the old one ("App not
 *    installed"), with no recovery short of uninstalling and losing all app
 *    data. Signing against a keystore that lives *outside* the generated tree
 *    (`~/.android/debug.keystore` by default) removes that whole class of
 *    failure, and is what makes the GitHub-release updater in
 *    services/updater.ts able to install over itself.
 *
 *    Override for a real release key by exporting, or passing as -P:
 *      QREMOTE_RELEASE_KEYSTORE, QREMOTE_RELEASE_KEYSTORE_PASSWORD,
 *      QREMOTE_RELEASE_KEY_ALIAS, QREMOTE_RELEASE_KEY_PASSWORD
 *
 *    The resolution is written as Gradle source rather than baked in here on
 *    purpose: prebuild runs once, but the keystore has to be resolved on the
 *    machine that is actually building.
 *
 * 2. **A `.debug` application id suffix**, so a debug build installs
 *    side-by-side with the release one instead of replacing it (and taking its
 *    data with it).
 *
 * 3. **ARM-only native libraries.** A universal APK carries the New
 *    Architecture's C++ for all four ABIs and weighs ~107 MB; dropping the two
 *    x86 ones (emulator-only — no shipping Android phone has run x86 for
 *    years) takes it to roughly a third of that. Both ARM ABIs are kept so
 *    older 32-bit devices still install. Pass -PqremoteAllAbis to build the
 *    universal APK anyway, which is what you want for an x86_64 emulator.
 */

const SIGNING_CONFIG = `
        qremoteRelease {
            // Prefer -P properties, then env vars, then the machine's Android
            // debug keystore, then the template one that ships inside the
            // generated project (last resort — see the plugin doc comment for
            // why depending on it is a trap).
            def resolved = { name, fallback ->
                project.findProperty(name) ?: System.getenv(name) ?: fallback
            }
            def homeKeystore = new File(System.getProperty('user.home'), '.android/debug.keystore')
            def ksPath = resolved('QREMOTE_RELEASE_KEYSTORE', null)
            if (ksPath == null) {
                ksPath = homeKeystore.exists() ? homeKeystore.absolutePath : file('debug.keystore').absolutePath
            }
            storeFile file(ksPath)
            storePassword resolved('QREMOTE_RELEASE_KEYSTORE_PASSWORD', 'android')
            keyAlias resolved('QREMOTE_RELEASE_KEY_ALIAS', 'androiddebugkey')
            keyPassword resolved('QREMOTE_RELEASE_KEY_PASSWORD', 'android')
        }
`;

const ABI_FILTERS = `
        ndk {
            // See the plugin doc comment. -PqremoteAllAbis restores all four.
            if (!project.hasProperty('qremoteAllAbis')) {
                abiFilters 'arm64-v8a', 'armeabi-v7a'
            }
        }
`;

/** Anchor: the `defaultConfig { … }` line, to append the ndk block after. */
const DEFAULT_CONFIG_ANCHOR = `    defaultConfig {
`;

/** Anchor: the last line of the template's `signingConfigs { debug { … } }`. */
const SIGNING_ANCHOR = `            keyPassword 'android'
        }
`;

const DEBUG_BUILD_TYPE = `        debug {
            signingConfig signingConfigs.debug`;

const DEBUG_BUILD_TYPE_PATCHED = `        debug {
            signingConfig signingConfigs.debug
            // Side-by-side with the release install, so a debug build never
            // wipes the servers/settings of the one you actually use.
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"`;

const RELEASE_SIGNING = `            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`;

const RELEASE_SIGNING_PATCHED = `            // Signed against a keystore outside the generated tree — see
            // plugins/withAndroidBuildTweaks.js.
            signingConfig signingConfigs.qremoteRelease`;

/** Fail loudly at prebuild time rather than producing a subtly wrong project. */
function replaceOnce(contents, needle, replacement, label) {
  if (contents.includes(replacement)) return contents;
  if (!contents.includes(needle)) {
    throw new Error(
      `withAndroidBuildTweaks: could not find the ${label} anchor in app/build.gradle. ` +
        `The Expo/RN template changed — update plugins/withAndroidBuildTweaks.js.`,
    );
  }
  return contents.replace(needle, replacement);
}

module.exports = function withAndroidBuildTweaks(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error('withAndroidBuildTweaks: expected a Groovy app/build.gradle.');
    }
    let contents = cfg.modResults.contents;
    contents = replaceOnce(
      contents,
      SIGNING_ANCHOR,
      SIGNING_ANCHOR + SIGNING_CONFIG,
      'signingConfigs',
    );
    contents = replaceOnce(
      contents,
      RELEASE_SIGNING,
      RELEASE_SIGNING_PATCHED,
      'release signingConfig',
    );
    contents = replaceOnce(
      contents,
      DEBUG_BUILD_TYPE,
      DEBUG_BUILD_TYPE_PATCHED,
      'debug build type',
    );
    contents = replaceOnce(
      contents,
      DEFAULT_CONFIG_ANCHOR,
      DEFAULT_CONFIG_ANCHOR + ABI_FILTERS,
      'defaultConfig',
    );
    cfg.modResults.contents = contents;
    return cfg;
  });
};
