const { withAppBuildGradle, withGradleProperties } = require('expo/config-plugins');

/**
 * withAndroidBuildTweaks — the three things the generated Android project needs
 * that app.config.js has no field for.
 *
 * `android/` is generated by `expo prebuild` and git-ignored, so it cannot be
 * hand-edited: the next prebuild would silently drop the change. Anything that
 * must survive belongs here.
 *
 * 1. **A stable release signature.** The RN template's `release` build type is
 *    signed with `android/app/debug.keystore`, a file that is re-materialised
 *    by every prebuild. If that file ever differs between two prebuilds — a
 *    template bump, a different machine, CI — the signature changes, and
 *    Android refuses to install the new APK over the old one ("App not
 *    installed"), with no recovery short of uninstalling and losing all app
 *    data. Signing against a keystore that lives *outside* the generated tree
 *    (`~/.android/debug.keystore` by default) removes that whole class of
 *    failure, and is what makes the GitHub-release updater in
 *    services/updater.ts able to install over itself.
 *
 *    Override for a real release key by exporting, or passing as -P:
 *      QREMOTE_RELEASE_KEYSTORE, QREMOTE_RELEASE_KEYSTORE_PASSWORD,
 *      QREMOTE_RELEASE_KEY_ALIAS, QREMOTE_RELEASE_KEY_PASSWORD
 *
 *    The resolution is written as Gradle source rather than baked in here on
 *    purpose: prebuild runs once, but the keystore has to be resolved on the
 *    machine that is actually building.
 *
 * 2. **A `.debug` application id suffix**, so a debug build installs
 *    side-by-side with the release one instead of replacing it (and taking its
 *    data with it).
 *
 * 3. **ARM-only native libraries**, via `reactNativeArchitectures` in
 *    `android/gradle.properties`. A universal APK carries the New
 *    Architecture's C++ for all four ABIs and weighs 107 MB; dropping the two
 *    x86 ones (emulator-only — no shipping Android phone has run x86 for
 *    years) brings it to 64 MB. Both ARM ABIs are kept so older 32-bit devices
 *    still install.
 *
 *    It has to be this property and not `defaultConfig.ndk.abiFilters`: the
 *    React Native Gradle plugin derives its own abiFilters from
 *    `reactNativeArchitectures` and applies them later in the configuration
 *    phase, so a hand-written abiFilters block in build.gradle is silently
 *    overwritten — the build succeeds and still ships all four ABIs.
 *
 *    A command-line `-P` beats gradle.properties, so the template's own
 *    documented escape hatch still works:
 *      ./gradlew :app:assembleRelease -PreactNativeArchitectures=x86_64
 */

/** The ABIs any real Android phone actually uses. */
const ANDROID_ARCHITECTURES = 'arm64-v8a,armeabi-v7a';

const SIGNING_CONFIG = `
        qremoteRelease {
            // Prefer -P properties, then env vars, then the machine's Android
            // debug keystore, then the template one that ships inside the
            // generated project (last resort — see the plugin doc comment for
            // why depending on it is a trap).
            def resolved = { name, fallback ->
                project.findProperty(name) ?: System.getenv(name) ?: fallback
            }
            def homeKeystore = new File(System.getProperty('user.home'), '.android/debug.keystore')
            def ksPath = resolved('QREMOTE_RELEASE_KEYSTORE', null)
            if (ksPath == null) {
                ksPath = homeKeystore.exists() ? homeKeystore.absolutePath : file('debug.keystore').absolutePath
            }
            storeFile file(ksPath)
            storePassword resolved('QREMOTE_RELEASE_KEYSTORE_PASSWORD', 'android')
            keyAlias resolved('QREMOTE_RELEASE_KEY_ALIAS', 'androiddebugkey')
            keyPassword resolved('QREMOTE_RELEASE_KEY_PASSWORD', 'android')
        }
`;

/** Anchor: the last line of the template's `signingConfigs { debug { … } }`. */
const SIGNING_ANCHOR = `            keyPassword 'android'
        }
`;

const DEBUG_BUILD_TYPE = `        debug {
            signingConfig signingConfigs.debug`;

const DEBUG_BUILD_TYPE_PATCHED = `        debug {
            signingConfig signingConfigs.debug
            // Side-by-side with the release install, so a debug build never
            // wipes the servers/settings of the one you actually use.
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"`;

const RELEASE_SIGNING = `            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`;

const RELEASE_SIGNING_PATCHED = `            // Signed against a keystore outside the generated tree — see
            // plugins/withAndroidBuildTweaks.js.
            signingConfig signingConfigs.qremoteRelease`;

/** Fail loudly at prebuild time rather than producing a subtly wrong project. */
function replaceOnce(contents, needle, replacement, label) {
  if (contents.includes(replacement)) return contents;
  if (!contents.includes(needle)) {
    throw new Error(
      `withAndroidBuildTweaks: could not find the ${label} anchor in app/build.gradle. ` +
        `The Expo/RN template changed — update plugins/withAndroidBuildTweaks.js.`,
    );
  }
  return contents.replace(needle, replacement);
}

/** Narrow `reactNativeArchitectures` in android/gradle.properties. */
function withArmOnlyArchitectures(config) {
  return withGradleProperties(config, (cfg) => {
    const entry = cfg.modResults.find(
      (item) => item.type === 'property' && item.key === 'reactNativeArchitectures',
    );
    if (!entry) {
      throw new Error(
        'withAndroidBuildTweaks: reactNativeArchitectures is missing from ' +
          'android/gradle.properties. The Expo template changed — update this plugin.',
      );
    }
    entry.value = ANDROID_ARCHITECTURES;
    return cfg;
  });
}

function withBuildGradleTweaks(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error('withAndroidBuildTweaks: expected a Groovy app/build.gradle.');
    }
    let contents = cfg.modResults.contents;
    contents = replaceOnce(
      contents,
      SIGNING_ANCHOR,
      SIGNING_ANCHOR + SIGNING_CONFIG,
      'signingConfigs',
    );
    contents = replaceOnce(
      contents,
      RELEASE_SIGNING,
      RELEASE_SIGNING_PATCHED,
      'release signingConfig',
    );
    contents = replaceOnce(
      contents,
      DEBUG_BUILD_TYPE,
      DEBUG_BUILD_TYPE_PATCHED,
      'debug build type',
    );
    cfg.modResults.contents = contents;
    return cfg;
  });
}

module.exports = function withAndroidBuildTweaks(config) {
  return withArmOnlyArchitectures(withBuildGradleTweaks(config));
};
